import { type ReactNode } from "react"

import type { Metadata } from "next"

import "@app/styles/globals.css"
import { dmSans } from "@/shared/config"
import { Footer } from "@/widgets/footer"
import { Header } from "@/widgets/header"

export const metadata: Metadata = {
    title: {
        template: "%s | Portfolio",
        default: "Dorin",
    },
    description: "Generated by create next app",
}

interface RootLayoutProps {
    children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body className={`antialiased ${dmSans.variable}`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
